apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-api-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash-api-go
  template:
    metadata:
      labels:
        app: dash-api-go
    spec:
      containers:
      - name: api
        image: pibell-0.lan:5000/dash-api-go:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dashboard-volume
          mountPath: /mnt/dashboard-info
        env:
        - name: DASHBOARD_INPUT_DIR
          value: /mnt/dashboard-info
        - name: MESSAGES_FILE
          value: /mnt/dashboard-info/dashboard-messages.json
        - name: APPLICATIONINSIGHTS_INSTRUMENTATION_KEY
          valueFrom:
            secretKeyRef:
              name: dash-api-app-insights-key
              key: instrumentation_key
      volumes:
        - name: dashboard-volume
          persistentVolumeClaim:
            claimName: dashboard-pvc
