apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-weather
spec:
  schedule: "3/15 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetch-weather
            image: pibell-0.lan:5000/fetch-weather:latest
            imagePullPolicy: Always
            command:
            - python3
            - /app/main.py
            volumeMounts:
            - name: dashboard-volume
              mountPath: /mnt/dashboard-info
            env:
            - name: OUTPUT_DIR
              value: /mnt/dashboard-info
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-creds
                  key: api-key
            - name: OPENWEATHER_LAT
              valueFrom:
                secretKeyRef:
                  name: weather-creds
                  key: lat
            - name: OPENWEATHER_LNG
              valueFrom:
                secretKeyRef:
                  name: weather-creds
                  key: lon
          volumes:
            - name: dashboard-volume
              persistentVolumeClaim:
                claimName: dashboard-pvc
          restartPolicy: OnFailure
