apiVersion: v1
kind: Service
metadata:
  name: leaf-api
  namespace: default
spec:
  selector:
    app: leaf-api
  type: LoadBalancer
  ports:
    - name: docker-port
      protocol: TCP
      port: 8002
      targetPort: 8000
