apiVersion: batch/v1
kind: CronJob
metadata:
  name: leaf-status
spec:
  schedule: "0/15 7-21 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 180
      template:
        spec:
          containers:
          - name: leaf-status
            image: curlimages/curl:8.15.0
            imagePullPolicy: Always
            command:
             - curl
             - http://leaf-api:8002/status
          restartPolicy: OnFailure
