apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaf-api
  template:
    metadata:
      labels:
        app: leaf-api
    spec:
      containers:
      - name: api
        image: pibell-0.lan:5000/leaf-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: dashboard-volume
          mountPath: /mnt/dashboard-info
        env:
        - name: LEAF_REGION
          value: NE # NNA=USA, NE=Europe, NCI=Canada, NMA=Austrailia, NML=Japan
        - name: LEAF_USERNAME
          valueFrom:
            secretKeyRef:
              name: leaf-creds
              key: user
        - name: LEAF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: leaf-creds
              key: password
        - name: DASHBOARD_INPUT_DIR
          value: /mnt/dashboard-info
      volumes:
        - name: dashboard-volume
          persistentVolumeClaim:
            claimName: dashboard-pvc
